version: '3.8'

services:
  kinopoisk-api:
    build: .
    container_name: kinopoisk-random-movies
    ports:
      - "8000:8000"
    environment:
      - KINOPOISK_API_TOKEN=CHHSWYQ-MGZ413R-K8A2STZ-RH7AD6R
      - API_HOST=0.0.0.0
      - API_PORT=8000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge